import type { Theme, SxProps } from "@mui/material/styles";

export const teamAcquisitionStyles = {
  card: {
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: "8px",
    overflow: "hidden",
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    px: 2,
    py: 1.5,
    borderBottom: "1px solid #EAECF0",
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 0.8,
  },
  title: {
    fontSize: 13,
    fontWeight: 600,
    color: "#101828",
  },
  memberCount: {
    fontSize: 11,
    color: "#185FA5",
    fontWeight: 500,
  },
  subtitle: {
    fontSize: 11,
    color: "#667085",
    px: 2,
    py: 1,
    borderBottom: "1px solid #EAECF0",
  },
  tableHeader: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr 1.2fr 1.2fr 1fr",
    px: 2,
    py: 1,
    color: "#667085",
    fontSize: 11,
    fontWeight: 500,
    borderBottom: "1px solid #EAECF0",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr 1.2fr 1.2fr 1fr",
    px: 2,
    py: 1.1,
    alignItems: "center",
    fontSize: 12,
    borderBottom: "1px solid #EAECF0",
  },
  totalRow: {
    background: "#F8FAFC",
    fontWeight: 600,
  },
  nameCell: {
    display: "flex",
    alignItems: "center",
    gap: 0.8,
  },
  roleChip: {
    display: "inline-flex",
    alignItems: "center",
    px: 0.8,
    py: 0.15,
    borderRadius: "6px",
    fontSize: 11,
    fontWeight: 600,
  },
  numCell: {
    color: "#185FA5",
    fontSize: 12,
  },
  statusBadge: {
    display: "inline-flex",
    alignItems: "center",
    px: 1,
    py: 0.3,
    borderRadius: "12px",
    fontSize: 10,
    fontWeight: 500,
    backgroundColor: "#FEECEC",
    color: "#B42318",
  },
  statusBadgeMet: {
    backgroundColor: "#EAF3DE",
    color: "#27500A",
  },
  footerNote: {
    display: "flex",
    alignItems: "flex-start",
    gap: 0.8,
    px: 2,
    py: 1.2,
    fontSize: 11,
    color: "#667085",
  },
} satisfies Record<string, SxProps<Theme>>;
