import type { Theme, SxProps } from "@mui/material/styles";

export const teamDistStyles = {
  card: {
    background: "#FFFFFF",
    border: "1px solid #E4E7EC",
    borderRadius: "8px",
    p: 2.5,
  },
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    mb: 3,
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 0.8,
  },
  title: {
    fontSize: 13,
    fontWeight: 600,
    color: "#101828",
  },
  summaryText: {
    fontSize: 11,
    color: "#667085",
  },
  treeWrapper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  rootChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 0.8,
    backgroundColor: "#185FA5",
    color: "#FFFFFF",
    borderRadius: "8px",
    px: 2,
    py: 1,
    fontSize: 13,
    fontWeight: 600,
  },
  connectorVertical: {
    width: "1px",
    height: 20,
    backgroundColor: "#D0D5DD",
  },
  connectorHorizontalRow: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    position: "relative",
  },
  groupsRow: {
    display: "flex",
    justifyContent: "center",
    gap: 18,
    width: "100%",
    flexWrap: "wrap",
  },
  groupColumn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "stretch",
    minWidth: 190,
  },
  groupHeader: {
    display: "inline-flex",
    justifyContent: "center",
    alignSelf: "center",
    backgroundColor: "#EAF3FD",
    border: "1px solid #CFE3F7",
    borderRadius: "8px",
    px: 1.5,
    py: 0.7,
    fontSize: 12,
    fontWeight: 600,
    color: "#185FA5",
    mb: 1,
  },
  memberRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    border: "1px solid #E4E7EC",
    borderRadius: "8px",
    px: 1.5,
    py: 0.9,
    mb: 0.8,
    fontSize: 12.5,
    color: "#101828",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#F8FAFC",
    },
  },
  roleChip: {
    display: "inline-flex",
    alignItems: "center",
    px: 1,
    py: 0.2,
    borderRadius: "6px",
    fontSize: 10,
    fontWeight: 600,
  },
  footerNote: {
    display: "flex",
    alignItems: "flex-start",
    gap: 0.8,
    mt: 2,
    fontSize: 11,
    color: "#667085",
  },
} satisfies Record<string, SxProps<Theme>>;
