export const incentivesEndpoints = {
  calculateEmployeeIncentive: "/MIS/CalculateEmployeeIncentive",
  GetIncentiveSlabs: "/MIS/GetIncentiveSlabs",
  GetclientwiseRevenue: "MIS/GetclientwiseRevenue",
  GetclientwiseDetailsRevenue: "MIS/GetclientwiseDetailsRevenue",
  GetEmpwiseDetailsRevenue: "MIS/GetEmpwiseDetailsRevenue",
  GetClientAcquisition: "MIS/GetClientAcquisition",
  GetRevenueEmployeeType: "MIS/GetRevenueEmployeeType",
  GetClientAcquisitionReportingHead: "MIS/GetClientAcquisitionReportingHead",
  GetTeamDistribution: "MIS/GetTeamDistribution",
  GetTeamMultipleAndIncentiveSummary: "MIS/GetTeamMultipleandIncentiveSummary",
  GetTeamSummary: "MIS/GetTeamSummary",
  IncentiveCalculator: "MIS/IncentiveCalculator",
  GetSalesSummary: "MIS/GetSalesSummary",
  GetAnnualTargetDetails: "MIS/GetAnnualTargetDetails",
  GetCADAnnualTargetDetails: "MIS/GetCADAnnualTargetDetails",
  GetYearlyOverview: "MIS/GetYearlyOverview",
  GetYearlyClientwiseRevenue: "MIS/GetYearlyClientwiseRevenue",
  GetYearlyClientwiseDetailsRevenue: "MIS/GetYearlyClientwiseDetailsRevenue",
  GetYearlyEmpwiseDetailsRevenue: "MIS/GetYearlyEmpwiseDetailsRevenue",
  GetNewClientBusiness: "MIS/GetNewClientBusiness",
} as const;
